### ISSUE TITLE
Awesome work, thanks

### ISSUE THREAD

**Issue by danielo515** [friebetill/obsidian-file-diff#12]
I had the same exact problem,and I thought the same, thank you for taking the time.

**Comment by friebetill** [comment]
Thank you for your kind words! It's great to hear that the work on this project resonates with your experiences. Your support is much appreciated!

**Comment by AMTQ** [comment]
I spent several hours trying to find the reason for these conflicts, as I have the same problem with syncthing + Obsidian on mobile and laptop. But unfortunately I have not found the smoking gun, so I'm looking to streamline the process of removing the conflicts.
Or has any of you any idea why these conflicts happen? Is it just the speed/slowness of Syncthing?

**Comment by friebetill** [comment]
I switched to iCloud. I was initially hesitant because of my data. However, I found the setting to enable end-to-end encryption for iCloud data. I trust that it’s mathematically very difficult to decrypt, and I’ve only read good things about it online, stating that it is trustworthy. Since then, I haven’t had a single merge conflict. This is because iCloud’s sync is instant, while Syncthing has some delay

Source: https://www.reddit.com/r/privacy/s/b5PWUBR4jt
